allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - core-js
  - esbuild
  - prisma
  - unrs-resolver
  - workerd
