name = "guyub"
main = ".open-next/worker.js"
account_id = "45efd648d755765f15c147660432044a"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[vars]
ENVIRONMENT = "production"
NEXTAUTH_URL = "https://guyub.thedreamcompany.space"
NEXT_PUBLIC_URL = "https://guyub.thedreamcompany.space"
NEXT_PUBLIC_TRAKTEER_SLUG = "brokado"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "guyub.thedreamcompany.space"
custom_domain = true
zone_name = "thedreamcompany.space"

[observability]
enabled = true
