name = "guyub"
type = "javascript"
account_id = "45efd648d755765f15c147660432044a"
workers_dev = false

# Build configuration for Cloudflare Pages
[build]
command = "pnpm build"
cwd = "./"
root_dir = ".next"

# Environment for production
[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.routes]
pattern = "guyub.thedreamcompany.space"
zone_name = "thedreamcompany.space"
